return {
	{
		"nvim-treesitter/nvim-treesitter",
		lazy = false,
		branch = "main",
		build = ":TSUpdate",
		config = function()
			require("nvim-treesitter.config").setup({
				ensure_installed = {
					"awk",
					"bash",
					"css",
					"csv",
					"dockerfile",
					"eex",
					"elixir",
					"fsharp",
					"go",
					"gomod",
					"gowork",
					"heex",
					"html",
					"ini",
					"java",
					"json",
					"latex",
					"lua",
					"markdown",
					"markdown_inline",
					"mermaid",
					"proto",
					"python",
					"regex",
					"rust",
					"sql",
					"sxhkdrc",
					"toml",
					"typescript",
					"xml",
					"yaml",
				},
				auto_install = true,
				highlight = { enable = true },
				indent = { enable = true },
			})
		end,
	},
}
